# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Restore MySql Image Cache if it exists
      id: cache-docker-mysql
      uses: actions/cache@v3
      with:
        path: ci/cache/docker/mysql
        key: cache-docker-mysql-5.7

    - name: Update MySql Image Cache if cache miss
      if: steps.cache-docker-redis.outputs.cache-hit != 'true'
      run: docker pull mysql:5.7 && mkdir -p ci/cache/docker/mysql && docker image save mysql:5.7  --output ./ci/cache/docker/mysql/mysql5.7.tar

    - name: Use MySql Image Cache if cache hit
      if: steps.cache-docker-mysql.outputs.cache-hit == 'true'
      run: docker image load --input ./ci/cache/docker/mysql/mysql5.7.tar

    - name: Start containers
      run: cd ./script && ./mysql-start.sh

    - name: Test with Maven
      run: mvn clean test

